### PR TITLE
Gracefully handle required missing retire arguments

### LINKED ISSUE #253: Error on 'retire' command
I get the following error when I attempt to run the command `rebar3 hex retire`:

```erlang
Error: badarg
[{unicode,characters_to_binary,
          [{error,{required,pkg}}],
          [{file,"unicode.erl"},
           {line,898},
           {error_info,#{module => erl_stdlib_errors}}]},
 {rebar3_hex_retire,handle_command,2,
                    [{file,"/Users/oubiwann/.cache/rebar3/plugins/rebar3_hex/src/rebar3_hex_retire.erl"},
                     {line,51}]},
 {rebar_core,do,2,
             [{file,"/home/runner/work/rebar3/rebar3/src/rebar_core.erl"},
              {line,155}]},
 {rebar_prv_do,do_task,5,
               [{file,"/home/runner/work/rebar3/rebar3/src/rebar_prv_do.erl"},
                {line,87}]},
 {rebar_core,do,2,
             [{file,"/home/runner/work/rebar3/rebar3/src/rebar_core.erl"},
              {line,155}]},
 {rebar3,run_aux,2,
         [{file,"/home/runner/work/rebar3/rebar3/src/rebar3.erl"},{line,182}]},
 {rebar3,main,1,
         [{file,"/home/runner/work/rebar3/rebar3/src/rebar3.erl"},{line,66}]},
 {escript,run,2,[{file,"escript.erl"},{line,750}]}]
```

I have attempted this with two different combinations of versions, both of which fail:

* Combo 1: Erlang 23, rebar 3.15.2
* Combo 2: Erlang 24, rebar 3.16.1

I have  only tried this on an old Mac laptop (10.13); I'll give it a try on a newer machine and provide an update.

### PR DESCRIPTION
**Pull request by starbelly**
Closes #253 

- Add helper function in rebar3_hex_retire that gets a required param or raises
- add basic tests for retire in integration suite
- add post retirement route support in hex api model

### CODE REVIEW

File: test/support/hex_api_model.erl [hunk 1]
```diff
@@ -139,6 +139,16 @@ handle('POST', [<<"repos">>, _Repo, <<"publish">>], Req) ->
...
    end;
 
+handle('POST', [<<"packages">>,_Name,<<"releases">>,_Ver,<<"retire">>], Req) ->
+    case authenticate(Req) of
+       {ok, #{username := _Username, email := _Email}} ->
+            {204, [{<<"Content-type">>, "text/plain"}], <<>>};
+       unauthorized ->
+            respond_with(403, Req, #{<<"message">> => <<"account not authorized for this action">>});
+        error ->
+           respond_with(401, Req, #{})
```
Comment (paulo-ferraz-oliveira) [inline test/support/hex_api_model.erl]:
```suggestion
            respond_with(401, Req, #{})
```

**Review by paulo-ferraz-oliveira — APPROVED** [review]

**Comment by oubiwann** [comment]
Any chance of a point release with this fix in it? :-D

**Comment by starbelly** [comment]
@oubiwann Yup, v6.11.6 released.
