### PR TITLE
Don't tell user to run with DIAGNOSTIC=1 when running with DIAGNOSTIC=1

### LINKED ISSUE #344: Don't show DIAGNOSTIC message if run with it set
If there is an exception that isn't handled then even when running with `DIAGNOSTIC=` you get the message:

```
===> An unknown error was encountered. Run with DIAGNOSTIC=1 for more details.
```

I think this should be left out if its already enabled.

### PR DESCRIPTION
**Pull request by starbelly**
Closes #344

### CODE REVIEW

File: src/rebar3_hex_error.erl [hunk 1]
```diff
@@ -32,4 +32,9 @@ format_error({Cmd, {error, {failed_connect, [{to_address,_},
 
 format_error(Reason) ->
     rebar_log:log(diagnostic, "Unknown error: ~p", [Reason]),
-    "An unknown error was encountered. Run with DIAGNOSTIC=1 for more details.".
+    case rebar_log:get_level() of
+        4 ->
+            "An unknown error was encountered";
+        _ ->
+            "An unknown error was encountered. Run with DIAGNOSTIC=1 for more details."
```
Comment (starbelly) [inline src/rebar3_hex_error.erl:39]: It's arguable we should not do this at all. It was an attempt to be helpful, but perhaps it's a bit much.

**Review by ferd — APPROVED** [review]
